project_id = "oodjzqvfjcrqlrqohyrs"

[functions.firecrawl-ingest]
verify_jwt = false

[functions.college-ingest]
verify_jwt = false

[functions.dev-auto-login]
verify_jwt = false

[functions.college-scorecard-import]
verify_jwt = false