// =============================================================================
// DO NOT EDIT THIS FILE THROUGH LOVABLE OR ANY AI-ASSISTED UI TOOL.
// This edge function uses direct API calls to Stripe Checkout.
// Editing through Lovable may revert it to the Lovable AI gateway, which is broken.
// All changes to this file must be made via direct GitHub commits or this environment.
// =============================================================================

import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import Stripe from "https://esm.sh/stripe@18.5.0";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const logStep = (step: string, details?: any) => {
  const detailsStr = details ? ` - ${JSON.stringify(details)}` : '';
  console.log(`[CREATE-CHECKOUT] ${step}${detailsStr}`);
};

// Premium subscription price ID ($19.99/month)
const PREMIUM_PRICE_ID = "price_1SySFGHqg2vAFif7Tr7U09V8";
// One-time onboarding fee ($199)
const ONBOARDING_PRICE_ID = "price_1SySarHqg2vAFif7T3Tksmom";

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseClient = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_ANON_KEY") ?? ""
  );

  try {
    logStep("Function started");

    const stripeKey = Deno.env.get("STRIPE_SECRET_KEY");
    if (!stripeKey) throw new Error("STRIPE_SECRET_KEY is not set");
    logStep("Stripe key verified");

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("No authorization header provided");

    const token = authHeader.replace("Bearer ", "");
    const { data } = await supabaseClient.auth.getUser(token);
    const user = data.user;
    if (!user?.email) throw new Error("User not authenticated or email not available");
    logStep("User authenticated", { email: user.email });

    const stripe = new Stripe(stripeKey, { apiVersion: "2025-08-27.basil" });
    
    // Check if customer already exists
    const customers = await stripe.customers.list({ email: user.email, limit: 1 });
    let customerId: string | undefined;
    let hasOnboarded = false;
    
    if (customers.data.length > 0) {
      customerId = customers.data[0].id;
      logStep("Existing customer found", { customerId });
      
      // Check if they've already paid the onboarding fee
      const payments = await stripe.paymentIntents.list({
        customer: customerId,
        limit: 100,
      });
      
      // Look for successful payment of the onboarding fee
      for (const payment of payments.data) {
        if (payment.status === 'succeeded' && payment.metadata?.onboarding_fee === 'true') {
          hasOnboarded = true;
          break;
        }
      }
      
      // Also check checkout sessions for the onboarding price
      const sessions = await stripe.checkout.sessions.list({
        customer: customerId,
        limit: 100,
      });
      
      for (const session of sessions.data) {
        if (session.payment_status === 'paid' && session.metadata?.includes_onboarding === 'true') {
          hasOnboarded = true;
          break;
        }
      }
    }

    const origin = req.headers.get("origin") || "http://localhost:5173";
    
    // Build line items - include onboarding fee only for new customers
    const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] = [];
    
    // Always include the subscription
    lineItems.push({
      price: PREMIUM_PRICE_ID,
      quantity: 1,
    });
    
    // Add onboarding fee for new customers who haven't paid it
    if (!hasOnboarded) {
      logStep("Including onboarding fee for new customer");
    }
    
    const session = await stripe.checkout.sessions.create({
      customer: customerId,
      customer_email: customerId ? undefined : user.email,
      line_items: hasOnboarded 
        ? lineItems 
        : [
            ...lineItems,
            {
              price: ONBOARDING_PRICE_ID,
              quantity: 1,
            },
          ],
      mode: "subscription",
      subscription_data: hasOnboarded ? undefined : {
        metadata: {
          onboarding_paid: 'true',
        },
      },
      metadata: {
        includes_onboarding: hasOnboarded ? 'false' : 'true',
      },
      success_url: `${origin}/dashboard?checkout=success`,
      cancel_url: `${origin}/dashboard?checkout=cancelled`,
    });

    logStep("Checkout session created", { sessionId: session.id });

    return new Response(JSON.stringify({ url: session.url }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 200,
    });
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    logStep("ERROR in create-checkout", { message: errorMessage });
    return new Response(JSON.stringify({ error: errorMessage }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
