// =============================================================================
// DO NOT EDIT THIS FILE THROUGH LOVABLE OR ANY AI-ASSISTED UI TOOL.
// This edge function uses direct API calls to OpenAI gpt-4.1-mini.
// Editing through Lovable may revert it to the Lovable AI gateway, which is broken.
// All changes to this file must be made via direct GitHub commits or this environment.
// =============================================================================

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// Model to use — gpt-4.1-mini is supported by the proxy
const AI_MODEL = "gpt-4.1-mini";

// OpenAI-compatible base URL (proxy supports gpt-4.1-mini, gpt-4.1-nano, gemini-2.5-flash)
const OPENAI_BASE_URL = "https://api.openai.com/v1";

interface ScoreBreakdown {
  category: string;
  score: number;
  maxScore: number;
  details: string;
}

interface MatchScoreResult {
  overall_score: number;
  eligibility_status: "eligible" | "maybe" | "ineligible";
  breakdown: ScoreBreakdown[];
  reasoning: string;
  missing_fields: string[];
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const openaiApiKey = Deno.env.get("OPENAI_API_KEY");

    if (!openaiApiKey) {
      throw new Error("OPENAI_API_KEY is not configured");
    }

    // Get auth token from request
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "No authorization header" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Create client with service key (bypasses RLS for reads/writes)
    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    
    // Verify user
    const { data: { user }, error: authError } = await supabase.auth.getUser(
      authHeader.replace("Bearer ", "")
    );
    
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Invalid token" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { type, scholarship_ids, college_ids } = await req.json();

    // Fetch user profile — also pull extended profile fields from profile_details if they exist
    const { data: profile, error: profileError } = await supabase
      .from("profiles")
      .select("*")
      .eq("id", user.id)
      .single();

    if (profileError || !profile) {
      return new Response(JSON.stringify({ error: "Profile not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Also try to get extended profile answers (scholarship questions)
    const { data: profileAnswers } = await supabase
      .from("profile_answers")
      .select("question_key, answer_value")
      .eq("user_id", user.id);

    // Merge profile answers into a flat object for easy access
    const extendedProfile: Record<string, unknown> = { ...profile };
    if (profileAnswers) {
      for (const ans of profileAnswers) {
        extendedProfile[ans.question_key] = ans.answer_value;
      }
    }

    let results: Record<string, MatchScoreResult> = {};

    if (type === "scholarships" && scholarship_ids?.length > 0) {
      const { data: scholarships, error: schError } = await supabase
        .from("scholarships")
        .select("*")
        .in("id", scholarship_ids);

      if (schError) throw schError;

      for (const scholarship of scholarships || []) {
        const score = await calculateScholarshipScore(extendedProfile, scholarship, openaiApiKey);
        results[scholarship.id] = score;
        
        // Store in database for caching
        await supabase.from("scholarship_matches").upsert({
          user_id: user.id,
          scholarship_id: scholarship.id,
          score: score.overall_score,
          eligibility_status: score.eligibility_status,
          reasons: score.reasoning,
          missing_fields: score.missing_fields,
        }, { onConflict: "user_id,scholarship_id" });
      }
    } else if (type === "colleges" && college_ids?.length > 0) {
      const { data: colleges, error: colError } = await supabase
        .from("colleges")
        .select("*")
        .in("id", college_ids);

      if (colError) throw colError;

      for (const college of colleges || []) {
        const score = await calculateCollegeScore(extendedProfile, college, openaiApiKey);
        results[college.id] = score;
        
        // Map score to bucket — DB constraint: 'Likely', 'Target', 'Reach' only
        let bucket = "Reach";
        if (score.overall_score >= 75) bucket = "Likely";
        else if (score.overall_score >= 50) bucket = "Target";

        // Store in database — only columns that exist in the schema
        await supabase.from("college_matches").upsert({
          student_id: user.id,
          college_id: college.id,
          fit_score: Math.round(score.overall_score),
          bucket,
          why_fit: score.reasoning,
        }, { onConflict: "student_id,college_id" });
      }
    }

    return new Response(JSON.stringify({ results }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error calculating match scores:", error);
    
    if (error instanceof Response) {
      const status = error.status;
      if (status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded. Please try again later." }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (status === 402) {
        return new Response(JSON.stringify({ error: "AI credits exhausted. Please add credits to continue." }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }
    
    return new Response(JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});

async function calculateScholarshipScore(
  profile: Record<string, unknown>,
  scholarship: Record<string, unknown>,
  apiKey: string
): Promise<MatchScoreResult> {
  // Build a rich profile summary from all available fields
  const profileSummary = buildProfileSummary(profile);

  const systemPrompt = `You are an expert college counselor and scholarship advisor. Analyze how well a student matches a scholarship's requirements.

Return structured scoring using the provided tool. Be specific about why the student matches or doesn't match each criterion.

Scoring guidelines:
- 90-100: Excellent match, meets all requirements with strong qualifications
- 70-89: Good match, meets most requirements
- 50-69: Moderate match, meets some requirements but has gaps
- 30-49: Weak match, significant gaps in eligibility
- 0-29: Poor match, likely ineligible

IMPORTANT: If a scholarship has a hard requirement the student clearly does NOT meet (e.g., need-based and student has no financial need, or requires specific ethnicity/identity the student doesn't have), score it 0-29 and mark as ineligible. Do not give moderate scores for clear disqualifications.

Consider both hard requirements (must meet) and soft preferences (nice to have).`;

  const userPrompt = `Evaluate this student's match for this scholarship:

STUDENT PROFILE:
${profileSummary}

SCHOLARSHIP:
- Name: ${scholarship.name}
- Amount: $${scholarship.amount_max_usd || scholarship.amount_usd || scholarship.amount_min_usd || "Varies"}
- Provider: ${scholarship.provider || "Unknown"}
- Description: ${scholarship.description || "No description"}
- Raw Eligibility Text: ${scholarship.raw_eligibility_text || "Not available"}
- Normalized Criteria: ${JSON.stringify(scholarship.normalized_criteria || {})}
- Tags: ${Array.isArray(scholarship.tags) ? (scholarship.tags as string[]).join(", ") : "None"}

Analyze eligibility and provide a match score.`;

  const response = await fetch(`${OPENAI_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: AI_MODEL,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      tools: [
        {
          type: "function",
          function: {
            name: "submit_scholarship_score",
            description: "Submit the scholarship match analysis results",
            parameters: {
              type: "object",
              properties: {
                overall_score: {
                  type: "number",
                  description: "Overall match score from 0-100",
                },
                eligibility_status: {
                  type: "string",
                  enum: ["eligible", "maybe", "ineligible"],
                  description: "eligible=meets requirements, maybe=possibly meets, ineligible=does not meet hard requirements",
                },
                breakdown: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      category: { type: "string", description: "Category name (Academic, Financial, Demographic, Extracurricular)" },
                      score: { type: "number", description: "Score for this category (0-25)" },
                      maxScore: { type: "number", description: "Maximum possible score (usually 25)" },
                      details: { type: "string", description: "Brief explanation" },
                    },
                    required: ["category", "score", "maxScore", "details"],
                  },
                },
                reasoning: {
                  type: "string",
                  description: "2-3 sentence summary of why this score was given",
                },
                missing_fields: {
                  type: "array",
                  items: { type: "string" },
                  description: "Profile fields the student should fill out to improve their score or confirm eligibility",
                },
              },
              required: ["overall_score", "eligibility_status", "breakdown", "reasoning", "missing_fields"],
            },
          },
        },
      ],
      tool_choice: { type: "function", function: { name: "submit_scholarship_score" } },
      temperature: 0.1,
    }),
  });

  if (!response.ok) {
    console.error("AI API error:", response.status, await response.text());
    return calculateDeterministicScholarshipScore(profile, scholarship);
  }

  const data = await response.json();
  const toolCall = data.choices?.[0]?.message?.tool_calls?.[0];
  
  if (!toolCall?.function?.arguments) {
    return calculateDeterministicScholarshipScore(profile, scholarship);
  }

  try {
    return JSON.parse(toolCall.function.arguments);
  } catch {
    return calculateDeterministicScholarshipScore(profile, scholarship);
  }
}

async function calculateCollegeScore(
  profile: Record<string, unknown>,
  college: Record<string, unknown>,
  apiKey: string
): Promise<MatchScoreResult> {
  const profileSummary = buildProfileSummary(profile);

  // acceptance_rate is stored as a percentage (e.g. 45.2 = 45.2%), not a decimal
  const accRate = college.acceptance_rate as number | null;
  const accDisplay = accRate != null ? `${accRate.toFixed(1)}%` : "Unknown";

  const systemPrompt = `You are an expert college admissions counselor. Analyze a student's chances of admission to a specific college.

Return structured scoring using the provided tool. Consider academic fit, financial fit, and overall match.

Score interpretation:
- 75-100: Likely/Safety school — student clearly exceeds typical admit profile
- 50-74: Target school — student is competitive, good chance
- 25-49: Reach school — student has a chance but is below typical admits
- 0-24: Unlikely — significant gap between student and typical admits

Be realistic but encouraging. Consider that holistic admissions look beyond just numbers.
When SAT/ACT data is unavailable for the college, use acceptance rate and school type as proxies.`;

  const userPrompt = `Evaluate this student's admission chances for this college:

STUDENT PROFILE:
${profileSummary}

COLLEGE:
- Name: ${college.name}
- Location: ${college.city}, ${college.state}
- Type: ${college.type || "Unknown"} (${college.setting || "Unknown"} setting)
- Acceptance Rate: ${accDisplay}
- SAT 25th-75th Percentile: ${college.sat_range_low || "?"}-${college.sat_range_high || "?"}
- ACT 25th-75th Percentile: ${college.act_range_low || "?"}-${college.act_range_high || "?"}
- Average GPA of Admitted Students: ${college.avg_gpa || "Unknown"}
- In-State Tuition: $${college.tuition_in_state || "Unknown"}
- Out-of-State Tuition: $${college.tuition_out_state || "Unknown"}
- Average Financial Aid Package: $${college.avg_financial_aid || "Unknown"}
- Graduation Rate: ${college.graduation_rate ? `${college.graduation_rate}%` : "Unknown"}
- Student Population: ${college.student_population || "Unknown"}

Analyze admission chances and fit.`;

  const response = await fetch(`${OPENAI_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: AI_MODEL,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      tools: [
        {
          type: "function",
          function: {
            name: "submit_college_score",
            description: "Submit the college admission analysis results",
            parameters: {
              type: "object",
              properties: {
                overall_score: {
                  type: "number",
                  description: "Overall admission chance score from 0-100",
                },
                eligibility_status: {
                  type: "string",
                  enum: ["eligible", "maybe", "ineligible"],
                  description: "eligible=safety/likely, maybe=target/reach, ineligible=unlikely",
                },
                breakdown: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      category: { type: "string", description: "Category name (Academic, Financial, Location, Activities)" },
                      score: { type: "number", description: "Score for this category (0-25)" },
                      maxScore: { type: "number", description: "Maximum possible score (usually 25)" },
                      details: { type: "string", description: "Brief explanation" },
                    },
                    required: ["category", "score", "maxScore", "details"],
                  },
                },
                reasoning: {
                  type: "string",
                  description: "2-3 sentence summary explaining the admission chances and fit",
                },
                missing_fields: {
                  type: "array",
                  items: { type: "string" },
                  description: "Profile fields that would help refine this assessment",
                },
              },
              required: ["overall_score", "eligibility_status", "breakdown", "reasoning", "missing_fields"],
            },
          },
        },
      ],
      tool_choice: { type: "function", function: { name: "submit_college_score" } },
      temperature: 0.1,
    }),
  });

  if (!response.ok) {
    console.error("AI API error:", response.status, await response.text());
    return calculateDeterministicCollegeScore(profile, college);
  }

  const data = await response.json();
  const toolCall = data.choices?.[0]?.message?.tool_calls?.[0];
  
  if (!toolCall?.function?.arguments) {
    return calculateDeterministicCollegeScore(profile, college);
  }

  try {
    return JSON.parse(toolCall.function.arguments);
  } catch {
    return calculateDeterministicCollegeScore(profile, college);
  }
}

/**
 * Build a human-readable profile summary from all available profile fields.
 * Handles both core profile columns and extended profile_answers.
 */
function buildProfileSummary(profile: Record<string, unknown>): string {
  const lines: string[] = [];

  // Academic
  if (profile.gpa_unweighted) lines.push(`- GPA (unweighted): ${profile.gpa_unweighted}`);
  if (profile.gpa_weighted) lines.push(`- GPA (weighted): ${profile.gpa_weighted}`);
  if (profile.gpa_scale) lines.push(`- GPA Scale: ${profile.gpa_scale}`);
  if (profile.class_rank) lines.push(`- Class Rank: ${profile.class_rank}`);
  if (profile.coursework_rigor) lines.push(`- Coursework Rigor: ${profile.coursework_rigor}`);
  if (profile.sat_score) lines.push(`- SAT Score: ${profile.sat_score}`);
  if (profile.act_score) lines.push(`- ACT Score: ${profile.act_score}`);
  if (profile.psat_score) lines.push(`- PSAT Score: ${profile.psat_score}`);
  if (Array.isArray(profile.ap_courses) && (profile.ap_courses as unknown[]).length > 0) {
    lines.push(`- AP Courses: ${(profile.ap_courses as string[]).length} courses (${(profile.ap_courses as string[]).join(", ")})`);
  }

  // Personal
  if (profile.state || profile.region) lines.push(`- Location: ${profile.state || ""} ${profile.region || ""}`.trim());
  if (profile.graduation_year) lines.push(`- Graduation Year: ${profile.graduation_year}`);
  if (profile.school) lines.push(`- High School: ${profile.school}`);
  if (profile.citizenship) lines.push(`- Citizenship: ${profile.citizenship}`);

  // Financial & demographic (from profile_answers)
  if (profile.first_gen !== undefined) lines.push(`- First-Generation College Student: ${profile.first_gen ? "Yes" : "No"}`);
  if (profile.need_based !== undefined) lines.push(`- Financial Need: ${profile.need_based ? "Yes" : "No"}`);
  if (profile.budget_max_usd) lines.push(`- Max Budget: $${profile.budget_max_usd}`);
  if (profile.race_ethnicity) lines.push(`- Race/Ethnicity: ${Array.isArray(profile.race_ethnicity) ? (profile.race_ethnicity as string[]).join(", ") : profile.race_ethnicity}`);

  // Interests & goals
  if (Array.isArray(profile.intended_majors) && (profile.intended_majors as unknown[]).length > 0) {
    lines.push(`- Intended Majors: ${(profile.intended_majors as string[]).join(", ")}`);
  }
  if (profile.career_goals) lines.push(`- Career Goals: ${Array.isArray(profile.career_goals) ? (profile.career_goals as string[]).join(", ") : profile.career_goals}`);
  if (profile.interests) lines.push(`- Interests: ${profile.interests}`);
  if (profile.values) lines.push(`- Values: ${profile.values}`);

  // Extracurriculars (from profile_answers)
  if (profile.volunteer_hours) lines.push(`- Volunteer Hours: ${profile.volunteer_hours}`);
  if (profile.athletics) lines.push(`- Athletics: ${Array.isArray(profile.athletics) ? (profile.athletics as string[]).join(", ") : profile.athletics}`);
  if (profile.state_resident) lines.push(`- State of Residence: ${profile.state_resident}`);

  // Leadership, awards, sports (may come from extended profile or direct fields)
  if (Array.isArray(profile.leadership_roles) && (profile.leadership_roles as unknown[]).length > 0) {
    lines.push(`- Leadership Roles: ${(profile.leadership_roles as string[]).join(", ")}`);
  }
  if (Array.isArray(profile.awards) && (profile.awards as unknown[]).length > 0) {
    lines.push(`- Awards: ${(profile.awards as string[]).join(", ")}`);
  }
  if (Array.isArray(profile.sports_played) && (profile.sports_played as unknown[]).length > 0) {
    lines.push(`- Sports: ${(profile.sports_played as string[]).join(", ")}`);
  }

  if (lines.length === 0) {
    return "- Profile incomplete — no data available";
  }

  return lines.join("\n");
}

// ── FALLBACK DETERMINISTIC SCORING ───────────────────────────────────────────

function calculateDeterministicScholarshipScore(
  profile: Record<string, unknown>,
  scholarship: Record<string, unknown>
): MatchScoreResult {
  const criteria = (scholarship.normalized_criteria || {}) as Record<string, unknown>;
  const breakdown: ScoreBreakdown[] = [];
  const missingFields: string[] = [];

  // Academic (25 pts)
  let academicScore = 20;
  if (criteria.min_gpa && profile.gpa_unweighted) {
    academicScore = (profile.gpa_unweighted as number) >= (criteria.min_gpa as number) ? 25 : 10;
  } else if (criteria.min_gpa && !profile.gpa_unweighted) {
    missingFields.push("gpa_unweighted");
  }
  breakdown.push({ category: "Academic", score: academicScore, maxScore: 25, details: "GPA and test score match" });

  // Financial (25 pts)
  let financialScore = 20;
  if (criteria.need_based && !profile.need_based) {
    missingFields.push("financial_need");
    financialScore = 15;
  }
  if (criteria.first_gen && !profile.first_gen) {
    missingFields.push("first_gen_college");
  }
  breakdown.push({ category: "Financial", score: financialScore, maxScore: 25, details: "Financial eligibility" });

  // Demographic (25 pts)
  breakdown.push({ category: "Demographic", score: 20, maxScore: 25, details: "Location and citizenship match" });

  // Extracurricular (25 pts)
  breakdown.push({ category: "Extracurricular", score: 20, maxScore: 25, details: "Activities and leadership" });

  const totalScore = breakdown.reduce((sum, b) => sum + b.score, 0);

  return {
    overall_score: totalScore,
    eligibility_status: totalScore >= 70 ? "eligible" : totalScore >= 40 ? "maybe" : "ineligible",
    breakdown,
    reasoning: `Based on available profile data, this appears to be a ${totalScore >= 70 ? "good" : totalScore >= 40 ? "possible" : "challenging"} match.${missingFields.length > 0 ? ` Complete ${missingFields.join(", ")} for a more accurate assessment.` : ""}`,
    missing_fields: missingFields,
  };
}

function calculateDeterministicCollegeScore(
  profile: Record<string, unknown>,
  college: Record<string, unknown>
): MatchScoreResult {
  const breakdown: ScoreBreakdown[] = [];
  const missingFields: string[] = [];

  // Academic (25 pts)
  let academicScore = 15;
  if (profile.sat_score && college.sat_range_low && college.sat_range_high) {
    const sat = profile.sat_score as number;
    const mid = ((college.sat_range_low as number) + (college.sat_range_high as number)) / 2;
    if (sat >= (college.sat_range_high as number)) academicScore = 25;
    else if (sat >= mid) academicScore = 20;
    else if (sat >= (college.sat_range_low as number)) academicScore = 15;
    else academicScore = 8;
  } else if (!profile.sat_score) {
    missingFields.push("sat_score");
  }
  breakdown.push({ category: "Academic", score: academicScore, maxScore: 25, details: "Test scores vs requirements" });

  // Financial (25 pts)
  let financialScore = 18;
  const budget = (profile.budget_max_usd as number) || 0;
  const isInState = profile.state === college.state;
  const tuition = ((isInState ? college.tuition_in_state : college.tuition_out_state) as number) || 0;
  const aid = (college.avg_financial_aid as number) || 0;
  if (budget && tuition) {
    const net = tuition - aid;
    if (net <= budget) financialScore = 25;
    else if (net <= budget * 1.25) financialScore = 18;
    else financialScore = 10;
  }
  breakdown.push({ category: "Financial", score: financialScore, maxScore: 25, details: "Cost vs budget" });

  // Location (25 pts)
  const locationScore = isInState ? 25 : 18;
  breakdown.push({ category: "Location", score: locationScore, maxScore: 25, details: isInState ? "In-state (lower tuition)" : "Out-of-state" });

  // Activities (25 pts)
  breakdown.push({ category: "Activities", score: 18, maxScore: 25, details: "Extracurricular fit" });

  const totalScore = breakdown.reduce((sum, b) => sum + b.score, 0);
  let bucket = "Reach";
  if (totalScore >= 75) bucket = "Likely";
  else if (totalScore >= 50) bucket = "Target";

  return {
    overall_score: totalScore,
    eligibility_status: totalScore >= 75 ? "eligible" : totalScore >= 50 ? "maybe" : "ineligible",
    breakdown,
    reasoning: `Based on available data, this college appears to be a ${bucket.toLowerCase()} school for you.`,
    missing_fields: missingFields,
  };
}
