// DO NOT EDIT THIS FILE THROUGH LOVABLE - uses real essays DB table
import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { FileText, Plus, Clock, Pencil, Trash2, FolderOpen, Sparkles, Loader2 } from "lucide-react";
import { EssayCoach } from "@/components/subscription/EssayCoach";
import { ApplicationMaterialsHub } from "@/components/application/ApplicationMaterialsHub";

type EssayStatus = "draft" | "in-progress" | "complete";
type EssayType = "personal_statement" | "scholarship" | "short_answer" | "supplemental";

interface Essay {
  id: string;
  title: string;
  essay_type: EssayType;
  prompt: string | null;
  content: string;
  status: EssayStatus;
  tags: string[];
  created_at: string;
  updated_at: string;
}

const typeLabels: Record<EssayType, string> = {
  personal_statement: "Personal Statement",
  scholarship: "Scholarship Essay",
  short_answer: "Short Answer",
  supplemental: "Supplemental",
};

const statusVariant: Record<EssayStatus, "secondary" | "default" | "success"> = {
  draft: "secondary",
  "in-progress": "default",
  complete: "success",
};

export default function Essays() {
  const { session } = useAuth();
  const [activeTab, setActiveTab] = useState("essays");
  const [coachEssayText, setCoachEssayText] = useState("");
  const [essays, setEssays] = useState<Essay[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [selectedEssay, setSelectedEssay] = useState<Essay | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editContent, setEditContent] = useState("");
  const [newEssayOpen, setNewEssayOpen] = useState(false);
  const [newEssay, setNewEssay] = useState({
    title: "",
    type: "personal_statement" as EssayType,
    prompt: "",
  });

  const loadEssays = useCallback(async () => {
    if (!session?.user) return;
    setLoading(true);
    const { data, error } = await supabase
      .from("essays")
      .select("*")
      .eq("user_id", session.user.id)
      .order("updated_at", { ascending: false });
    if (error) toast.error("Failed to load essays");
    else setEssays((data ?? []) as Essay[]);
    setLoading(false);
  }, [session]);

  useEffect(() => {
    if (session?.user) void loadEssays();
  }, [session, loadEssays]);

  const handleSendToCoach = (text: string) => {
    setCoachEssayText(text);
    setActiveTab("coach");
  };

  async function handleCreateEssay() {
    if (!newEssay.title.trim() || !session?.user) return;
    const { data, error } = await supabase
      .from("essays")
      .insert({ user_id: session.user.id, title: newEssay.title, essay_type: newEssay.type, prompt: newEssay.prompt || null, content: "", status: "draft", tags: [] })
      .select().single();
    if (error) toast.error("Failed to create essay");
    else { setEssays(prev => [data as Essay, ...prev]); setNewEssayOpen(false); setNewEssay({ title: "", type: "personal_statement", prompt: "" }); toast.success("Essay created!"); }
  }

  async function handleSaveContent() {
    if (!selectedEssay || !session?.user) return;
    setSaving(true);
    const wc = editContent.trim().split(/\s+/).filter(Boolean).length;
    const newStatus: EssayStatus = wc > 0 ? "in-progress" : "draft";
    const { error } = await supabase.from("essays").update({ content: editContent, status: newStatus, updated_at: new Date().toISOString() }).eq("id", selectedEssay.id).eq("user_id", session.user.id);
    if (error) toast.error("Failed to save");
    else { setEssays(prev => prev.map(e => e.id === selectedEssay.id ? { ...e, content: editContent, status: newStatus } : e)); setSelectedEssay(prev => prev ? { ...prev, content: editContent, status: newStatus } : null); setIsEditing(false); toast.success("Saved!"); }
    setSaving(false);
  }

  async function handleDeleteEssay(id: string) {
    if (!session?.user) return;
    const { error } = await supabase.from("essays").delete().eq("id", id).eq("user_id", session.user.id);
    if (error) toast.error("Failed to delete");
    else { setEssays(prev => prev.filter(e => e.id !== id)); if (selectedEssay?.id === id) setSelectedEssay(null); toast.success("Deleted"); }
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Essays & Application Materials</h1>
          <p className="text-muted-foreground mt-1">
            Manage your essays, upload supporting materials, and get AI-powered guidance.
          </p>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-3 max-w-md">
          <TabsTrigger value="essays" className="flex items-center gap-1.5">
            <FileText className="h-4 w-4" />
            Essays
          </TabsTrigger>
          <TabsTrigger value="materials" className="flex items-center gap-1.5">
            <FolderOpen className="h-4 w-4" />
            Materials
          </TabsTrigger>
          <TabsTrigger value="coach" className="flex items-center gap-1.5">
            <Sparkles className="h-4 w-4" />
            AI Coach
          </TabsTrigger>
        </TabsList>

        <TabsContent value="essays" className="mt-6">
          <div className="flex justify-end mb-4">
            <Dialog open={newEssayOpen} onOpenChange={setNewEssayOpen}>
              <DialogTrigger asChild>
                <Button>
                  <Plus className="h-4 w-4 mr-2" />
                  New Essay
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Create New Essay</DialogTitle>
                  <DialogDescription>Add a new essay or writing piece to your library.</DialogDescription>
                </DialogHeader>
                <div className="space-y-4 pt-4">
                  <div className="space-y-2">
                    <Label>Title</Label>
                    <Input
                      value={newEssay.title}
                      onChange={(e) => setNewEssay((p) => ({ ...p, title: e.target.value }))}
                      placeholder="e.g., Common App Personal Statement"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>Type</Label>
                    <Select
                      value={newEssay.type}
                      onValueChange={(v) => setNewEssay((p) => ({ ...p, type: v as EssayType }))}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {Object.entries(typeLabels).map(([key, label]) => (
                          <SelectItem key={key} value={key}>
                            {label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label>Prompt (optional)</Label>
                    <Textarea
                      value={newEssay.prompt}
                      onChange={(e) => setNewEssay((p) => ({ ...p, prompt: e.target.value }))}
                      placeholder="Enter the essay prompt..."
                      rows={3}
                    />
                  </div>
                  <Button onClick={handleCreateEssay} className="w-full">
                    Create Essay
                  </Button>
                </div>
              </DialogContent>
            </Dialog>
          </div>

          <div className="grid lg:grid-cols-3 gap-6">
        {/* Essay List */}
        <div className="lg:col-span-1 space-y-3">
          <h3 className="font-semibold text-foreground">Your Essays ({essays.length})</h3>
          {essays.length === 0 ? (
            <Card className="p-6 text-center">
              <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-3" />
              <p className="text-muted-foreground">No essays yet. Create your first one!</p>
            </Card>
          ) : (
            essays.map((essay) => (
              <Card
                key={essay.id}
                className={`cursor-pointer transition-all hover:border-primary/50 ${
                  selectedEssay?.id === essay.id ? "border-primary ring-1 ring-primary/20" : ""
                }`}
                onClick={() => {
                  setSelectedEssay(essay);
                  setEditContent(essay.content);
                  setIsEditing(false);
                }}
              >
                <CardContent className="p-4">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1 min-w-0">
                      <h4 className="font-medium text-foreground truncate">{essay.title}</h4>
                      <p className="text-sm text-muted-foreground">{typeLabels[essay.essay_type]}</p>
                    </div>
                    <Badge variant={statusVariant[essay.status]} size="sm">
                      {essay.status.replace("-", " ")}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-3 mt-2 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Clock className="h-3 w-3" />
                      {new Date(essay.updated_at).toLocaleDateString()}
                    </span>
                    <span>{essay.content.trim().split(/\s+/).filter(Boolean).length} words</span>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>

        {/* Essay Editor */}
        <div className="lg:col-span-2">
          {selectedEssay ? (
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-4">
                <div className="flex-1">
                  <CardTitle>{selectedEssay.title}</CardTitle>
                  <CardDescription className="mt-1">
                    {selectedEssay.prompt || "No prompt specified"}
                  </CardDescription>
                  <div className="flex items-center gap-2 mt-2">
                    <Badge variant={statusVariant[selectedEssay.status]}>
                      {selectedEssay.status.replace("-", " ")}
                    </Badge>
                    <span className="text-sm text-muted-foreground">
                      {selectedEssay.content.trim().split(/\s+/).filter(Boolean).length} words
                    </span>
                  </div>
                </div>
                <div className="flex gap-2">
                  {isEditing ? (
                    <>
                      <Button size="sm" variant="outline" onClick={() => setIsEditing(false)}>
                        Cancel
                      </Button>
                      <Button size="sm" onClick={handleSaveContent}>
                        Save
                      </Button>
                    </>
                  ) : (
                    <>
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => setIsEditing(true)}
                      >
                        <Pencil className="h-4 w-4 mr-1" />
                        Edit
                      </Button>
                      {selectedEssay.content && (
                        <Button
                          size="sm"
                          variant="outline"
                          className="text-primary border-primary/30 hover:bg-primary/10"
                          onClick={() => handleSendToCoach(selectedEssay.content)}
                        >
                          <Sparkles className="h-4 w-4 mr-1" />
                          AI Review
                        </Button>
                      )}
                      <Button
                        size="sm"
                        variant="ghost"
                        className="text-destructive hover:text-destructive"
                        onClick={() => handleDeleteEssay(selectedEssay.id)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </>
                  )}
                </div>
              </CardHeader>
              <CardContent>
                {isEditing ? (
                  <Textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    placeholder="Start writing your essay..."
                    className="min-h-[400px] resize-y"
                  />
                ) : (
                  <div className="min-h-[400px] p-4 rounded-lg bg-muted/30 border">
                    {selectedEssay.content ? (
                      <p className="whitespace-pre-wrap text-foreground">{selectedEssay.content}</p>
                    ) : (
                      <p className="text-muted-foreground italic">
                        No content yet. Click Edit to start writing.
                      </p>
                    )}
                  </div>
                )}
              </CardContent>
            </Card>
          ) : (
            <Card className="h-[500px] flex items-center justify-center">
              <div className="text-center">
                <FileText className="h-16 w-16 text-muted-foreground mx-auto mb-4" />
                <h3 className="text-lg font-medium text-foreground mb-1">Select an Essay</h3>
                <p className="text-muted-foreground">Choose an essay from the list to view or edit</p>
              </div>
            </Card>
          )}
        </div>
          </div>
        </TabsContent>

        <TabsContent value="materials" className="mt-6">
          <ApplicationMaterialsHub />
        </TabsContent>

        <TabsContent value="coach" className="mt-6">
          <div className="max-w-2xl">
            <EssayCoach initialEssayText={coachEssayText} />
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
