// DO NOT EDIT THIS FILE THROUGH LOVABLE OR ANY AI-ASSISTED UI TOOL.
// This page implements the SAT/ACT practice test feature with real question data.
// All changes must be made via direct GitHub commits or this environment.

import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import {
  BookOpen, Clock, CheckCircle2, XCircle, ChevronRight,
  ChevronLeft, Trophy, RotateCcw, BarChart3, Target, Zap,
  Brain, Calculator, FileText, FlaskConical,
} from "lucide-react";

interface Question {
  id: string;
  test_type: "SAT" | "ACT";
  section: string;
  difficulty: "easy" | "medium" | "hard";
  question_text: string;
  passage_text: string | null;
  answer_choices: { key: string; text: string }[];
  correct_answer: string;
  explanation: string;
  skill_tag: string | null;
}

interface AttemptQuestion {
  question_id: string;
  user_answer: string | null;
  correct: boolean | null;
  time_spent_sec: number;
}

interface TestResult {
  score_raw: number;
  total_questions: number;
  score_pct: number;
  score_scaled: number;
  section_scores: Record<string, { correct: number; total: number }>;
  skill_breakdown: Record<string, { correct: number; total: number }>;
  questions_with_answers: (Question & { user_answer: string | null; correct: boolean })[];
}

interface PastAttempt {
  id: string;
  test_type: string;
  section: string | null;
  score_raw: number;
  score_scaled: number;
  total_questions: number;
  completed_at: string;
  section_scores: Record<string, { correct: number; total: number }> | null;
}

const SECTION_ICONS: Record<string, React.ElementType> = {
  reading_writing: FileText,
  math: Calculator,
  english: BookOpen,
  reading: BookOpen,
  science: FlaskConical,
};

const SECTION_LABELS: Record<string, string> = {
  reading_writing: "Reading & Writing",
  math: "Math",
  english: "English",
  reading: "Reading",
  science: "Science",
};

const DIFFICULTY_COLORS: Record<string, string> = {
  easy: "bg-emerald-100 text-emerald-700",
  medium: "bg-amber-100 text-amber-700",
  hard: "bg-red-100 text-red-700",
};

// Scale raw score to SAT/ACT equivalent
function scaleScore(raw: number, total: number, testType: string, section?: string): number {
  const pct = raw / total;
  if (testType === "SAT") {
    // SAT section: 200–800
    return Math.round(200 + pct * 600);
  } else {
    // ACT: 1–36
    return Math.max(1, Math.round(1 + pct * 35));
  }
}

export default function PracticeTestPage() {
  const { session } = useAuth();
  const [activeTab, setActiveTab] = useState<"start" | "test" | "results" | "history">("start");
  const [testType, setTestType] = useState<"SAT" | "ACT">("SAT");
  const [selectedSection, setSelectedSection] = useState<string>("all");
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [startTime, setStartTime] = useState<Date | null>(null);
  const [questionStartTime, setQuestionStartTime] = useState<Date>(new Date());
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<TestResult | null>(null);
  const [showExplanation, setShowExplanation] = useState(false);
  const [pastAttempts, setPastAttempts] = useState<PastAttempt[]>([]);
  const [questionCount, setQuestionCount] = useState(10);

  const satSections = ["all", "reading_writing", "math"];
  const actSections = ["all", "english", "math", "reading", "science"];
  const sections = testType === "SAT" ? satSections : actSections;

  const loadPastAttempts = useCallback(async () => {
    if (!session?.user) return;
    const { data } = await supabase
      .from("student_test_attempts")
      .select("id, test_type, section, score_raw, score_scaled, total_questions, completed_at, section_scores")
      .eq("user_id", session.user.id)
      .eq("completed", true)
      .order("completed_at", { ascending: false })
      .limit(20);
    if (data) setPastAttempts(data as PastAttempt[]);
  }, [session]);

  useEffect(() => {
    if (session?.user) void loadPastAttempts();
  }, [session, loadPastAttempts]);

  async function startTest() {
    setLoading(true);
    try {
      let query = supabase
        .from("practice_test_questions")
        .select("*")
        .eq("test_type", testType)
        .eq("active", true);

      if (selectedSection !== "all") {
        query = query.eq("section", selectedSection);
      }

      const { data, error } = await query;
      if (error) throw error;
      if (!data || data.length === 0) {
        toast.error("No questions available for this selection.");
        setLoading(false);
        return;
      }

      // Shuffle and limit
      const shuffled = [...data].sort(() => Math.random() - 0.5).slice(0, questionCount);
      setQuestions(shuffled as Question[]);
      setAnswers({});
      setCurrentIndex(0);
      setResult(null);
      setShowExplanation(false);
      setStartTime(new Date());
      setQuestionStartTime(new Date());
      setActiveTab("test");
    } catch (err) {
      toast.error("Failed to load questions. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  function selectAnswer(questionId: string, answer: string) {
    setAnswers(prev => ({ ...prev, [questionId]: answer }));
  }

  function nextQuestion() {
    setShowExplanation(false);
    setQuestionStartTime(new Date());
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(prev => prev + 1);
    }
  }

  function prevQuestion() {
    setShowExplanation(false);
    setCurrentIndex(prev => Math.max(0, prev - 1));
  }

  async function submitTest() {
    const totalTime = startTime ? Math.round((Date.now() - startTime.getTime()) / 1000) : 0;

    // Build results
    const questionsWithAnswers = questions.map(q => ({
      ...q,
      user_answer: answers[q.id] ?? null,
      correct: answers[q.id] === q.correct_answer,
    }));

    const scoreRaw = questionsWithAnswers.filter(q => q.correct).length;
    const scorePct = Math.round((scoreRaw / questions.length) * 100);
    const scoreScaled = scaleScore(scoreRaw, questions.length, testType, selectedSection);

    // Section breakdown
    const sectionScores: Record<string, { correct: number; total: number }> = {};
    const skillBreakdown: Record<string, { correct: number; total: number }> = {};

    for (const q of questionsWithAnswers) {
      if (!sectionScores[q.section]) sectionScores[q.section] = { correct: 0, total: 0 };
      sectionScores[q.section].total++;
      if (q.correct) sectionScores[q.section].correct++;

      if (q.skill_tag) {
        if (!skillBreakdown[q.skill_tag]) skillBreakdown[q.skill_tag] = { correct: 0, total: 0 };
        skillBreakdown[q.skill_tag].total++;
        if (q.correct) skillBreakdown[q.skill_tag].correct++;
      }
    }

    const testResult: TestResult = {
      score_raw: scoreRaw,
      total_questions: questions.length,
      score_pct: scorePct,
      score_scaled: scoreScaled,
      section_scores: sectionScores,
      skill_breakdown: skillBreakdown,
      questions_with_answers: questionsWithAnswers,
    };

    setResult(testResult);
    setActiveTab("results");

    // Save to DB
    if (session?.user) {
      const attemptData = {
        user_id: session.user.id,
        test_type: testType,
        test_mode: "practice",
        section: selectedSection === "all" ? null : selectedSection,
        questions: questionsWithAnswers.map(q => ({
          question_id: q.id,
          user_answer: q.user_answer,
          correct: q.correct,
          time_spent_sec: 0,
        })),
        score_raw: scoreRaw,
        score_scaled: scoreScaled,
        total_questions: questions.length,
        time_spent_sec: totalTime,
        completed: true,
        completed_at: new Date().toISOString(),
        section_scores: sectionScores,
        skill_breakdown: skillBreakdown,
      };

      const { error } = await supabase.from("student_test_attempts").insert(attemptData);
      if (!error) loadPastAttempts();
    }
  }

  const currentQuestion = questions[currentIndex];
  const answeredCount = Object.keys(answers).length;
  const progress = questions.length > 0 ? ((currentIndex + 1) / questions.length) * 100 : 0;

  return (
    <div className="p-6 space-y-6 max-w-4xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Brain className="h-6 w-6 text-emerald-600" />
          SAT / ACT Practice
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          Real-format questions with detailed explanations. Track your progress over time.
        </p>
      </div>

      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as typeof activeTab)}>
        <TabsList className="grid w-full max-w-md grid-cols-3">
          <TabsTrigger value="start">Start Test</TabsTrigger>
          <TabsTrigger value="results" disabled={!result}>Results</TabsTrigger>
          <TabsTrigger value="history">History</TabsTrigger>
        </TabsList>

        {/* ── START TAB ── */}
        <TabsContent value="start" className="mt-6 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Configure Your Practice Session</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Test type */}
              <div>
                <p className="text-sm font-medium mb-3">Test Type</p>
                <div className="grid grid-cols-2 gap-3">
                  {(["SAT", "ACT"] as const).map(t => (
                    <button
                      key={t}
                      onClick={() => { setTestType(t); setSelectedSection("all"); }}
                      className={`p-4 rounded-lg border-2 text-left transition-all ${
                        testType === t
                          ? "border-emerald-500 bg-emerald-50"
                          : "border-border hover:border-emerald-300"
                      }`}
                    >
                      <div className="font-semibold text-lg">{t}</div>
                      <div className="text-xs text-muted-foreground mt-1">
                        {t === "SAT"
                          ? "Reading & Writing + Math (400–1600)"
                          : "English, Math, Reading, Science (1–36)"}
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Section */}
              <div>
                <p className="text-sm font-medium mb-3">Section</p>
                <div className="flex flex-wrap gap-2">
                  {sections.map(s => {
                    const Icon = SECTION_ICONS[s] ?? BookOpen;
                    return (
                      <button
                        key={s}
                        onClick={() => setSelectedSection(s)}
                        className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm border transition-all ${
                          selectedSection === s
                            ? "border-emerald-500 bg-emerald-50 text-emerald-700 font-medium"
                            : "border-border hover:border-emerald-300"
                        }`}
                      >
                        <Icon className="h-3.5 w-3.5" />
                        {s === "all" ? "All Sections" : SECTION_LABELS[s]}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Question count */}
              <div>
                <p className="text-sm font-medium mb-3">Number of Questions</p>
                <div className="flex gap-2">
                  {[5, 10, 15, 20].map(n => (
                    <button
                      key={n}
                      onClick={() => setQuestionCount(n)}
                      className={`px-4 py-2 rounded-lg border text-sm font-medium transition-all ${
                        questionCount === n
                          ? "border-emerald-500 bg-emerald-50 text-emerald-700"
                          : "border-border hover:border-emerald-300"
                      }`}
                    >
                      {n}
                    </button>
                  ))}
                </div>
              </div>

              <Button
                onClick={startTest}
                disabled={loading}
                className="w-full bg-emerald-600 hover:bg-emerald-700"
                size="lg"
              >
                {loading ? "Loading questions..." : `Start ${questionCount}-Question Practice`}
              </Button>
            </CardContent>
          </Card>

          {/* Info cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card className="bg-blue-50 border-blue-200">
              <CardContent className="p-4">
                <Target className="h-5 w-5 text-blue-600 mb-2" />
                <p className="font-medium text-sm">Real Format</p>
                <p className="text-xs text-muted-foreground mt-1">Questions modeled after actual SAT/ACT style and difficulty</p>
              </CardContent>
            </Card>
            <Card className="bg-purple-50 border-purple-200">
              <CardContent className="p-4">
                <Zap className="h-5 w-5 text-purple-600 mb-2" />
                <p className="font-medium text-sm">Instant Explanations</p>
                <p className="text-xs text-muted-foreground mt-1">Every question includes a detailed explanation of why the answer is correct</p>
              </CardContent>
            </Card>
            <Card className="bg-amber-50 border-amber-200">
              <CardContent className="p-4">
                <BarChart3 className="h-5 w-5 text-amber-600 mb-2" />
                <p className="font-medium text-sm">Progress Tracking</p>
                <p className="text-xs text-muted-foreground mt-1">See your score trends and skill-by-skill breakdown over time</p>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* ── TEST TAB ── */}
        <TabsContent value="test" className="mt-6">
          {currentQuestion && (
            <div className="space-y-4">
              {/* Header */}
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Badge variant="outline">{testType}</Badge>
                  <Badge variant="outline">{SECTION_LABELS[currentQuestion.section] ?? currentQuestion.section}</Badge>
                  <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${DIFFICULTY_COLORS[currentQuestion.difficulty]}`}>
                    {currentQuestion.difficulty}
                  </span>
                </div>
                <span className="text-sm text-muted-foreground">
                  {currentIndex + 1} / {questions.length}
                </span>
              </div>

              <Progress value={progress} className="h-2" />

              {/* Passage */}
              {currentQuestion.passage_text && (
                <Card className="bg-slate-50 border-slate-200">
                  <CardContent className="p-4">
                    <p className="text-sm leading-relaxed whitespace-pre-line">{currentQuestion.passage_text}</p>
                  </CardContent>
                </Card>
              )}

              {/* Question */}
              <Card>
                <CardContent className="p-6 space-y-5">
                  <p className="text-base font-medium leading-relaxed whitespace-pre-line">
                    {currentQuestion.question_text}
                  </p>

                  <RadioGroup
                    value={answers[currentQuestion.id] ?? ""}
                    onValueChange={(val) => selectAnswer(currentQuestion.id, val)}
                  >
                    <div className="space-y-2">
                      {currentQuestion.answer_choices.map(choice => {
                        const isSelected = answers[currentQuestion.id] === choice.key;
                        const isCorrect = choice.key === currentQuestion.correct_answer;
                        const showResult = showExplanation;

                        let choiceClass = "flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition-all hover:bg-accent";
                        if (showResult && isCorrect) choiceClass += " border-emerald-500 bg-emerald-50";
                        else if (showResult && isSelected && !isCorrect) choiceClass += " border-red-400 bg-red-50";
                        else if (isSelected) choiceClass += " border-emerald-400 bg-emerald-50";

                        return (
                          <div key={choice.key} className={choiceClass} onClick={() => !showExplanation && selectAnswer(currentQuestion.id, choice.key)}>
                            <RadioGroupItem value={choice.key} id={`choice-${choice.key}`} className="mt-0.5" />
                            <Label htmlFor={`choice-${choice.key}`} className="cursor-pointer flex-1 text-sm leading-relaxed">
                              <span className="font-semibold mr-2">{choice.key}.</span>
                              {choice.text}
                            </Label>
                            {showResult && isCorrect && <CheckCircle2 className="h-4 w-4 text-emerald-600 shrink-0 mt-0.5" />}
                            {showResult && isSelected && !isCorrect && <XCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />}
                          </div>
                        );
                      })}
                    </div>
                  </RadioGroup>

                  {/* Explanation */}
                  {showExplanation && (
                    <div className="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
                      <p className="text-sm font-semibold text-blue-800 mb-1">Explanation</p>
                      <p className="text-sm text-blue-900 leading-relaxed">{currentQuestion.explanation}</p>
                    </div>
                  )}

                  {/* Actions */}
                  <div className="flex items-center justify-between pt-2">
                    <Button variant="outline" size="sm" onClick={prevQuestion} disabled={currentIndex === 0}>
                      <ChevronLeft className="h-4 w-4 mr-1" /> Previous
                    </Button>

                    <div className="flex gap-2">
                      {answers[currentQuestion.id] && !showExplanation && (
                        <Button variant="outline" size="sm" onClick={() => setShowExplanation(true)}>
                          Check Answer
                        </Button>
                      )}
                      {currentIndex < questions.length - 1 ? (
                        <Button size="sm" onClick={nextQuestion} className="bg-emerald-600 hover:bg-emerald-700">
                          Next <ChevronRight className="h-4 w-4 ml-1" />
                        </Button>
                      ) : (
                        <Button
                          size="sm"
                          onClick={submitTest}
                          disabled={answeredCount < questions.length}
                          className="bg-emerald-600 hover:bg-emerald-700"
                        >
                          Submit Test ({answeredCount}/{questions.length} answered)
                        </Button>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Question nav dots */}
              <div className="flex flex-wrap gap-1.5 justify-center">
                {questions.map((q, i) => (
                  <button
                    key={q.id}
                    onClick={() => { setCurrentIndex(i); setShowExplanation(false); }}
                    className={`w-7 h-7 rounded-full text-xs font-medium transition-all ${
                      i === currentIndex
                        ? "bg-emerald-600 text-white"
                        : answers[q.id]
                        ? "bg-emerald-100 text-emerald-700 border border-emerald-300"
                        : "bg-muted text-muted-foreground border border-border"
                    }`}
                  >
                    {i + 1}
                  </button>
                ))}
              </div>
            </div>
          )}
        </TabsContent>

        {/* ── RESULTS TAB ── */}
        <TabsContent value="results" className="mt-6">
          {result && (
            <div className="space-y-6">
              {/* Score card */}
              <Card className="bg-gradient-to-br from-emerald-50 to-blue-50 border-emerald-200">
                <CardContent className="p-6 text-center">
                  <Trophy className="h-10 w-10 text-amber-500 mx-auto mb-3" />
                  <p className="text-sm text-muted-foreground mb-1">Your Score</p>
                  <p className="text-5xl font-bold text-emerald-700">{result.score_scaled}</p>
                  <p className="text-sm text-muted-foreground mt-1">
                    {testType === "SAT" ? "out of 800 (per section)" : "out of 36"}
                  </p>
                  <div className="flex items-center justify-center gap-4 mt-4">
                    <div className="text-center">
                      <p className="text-2xl font-bold">{result.score_raw}/{result.total_questions}</p>
                      <p className="text-xs text-muted-foreground">Correct</p>
                    </div>
                    <div className="text-center">
                      <p className="text-2xl font-bold">{result.score_pct}%</p>
                      <p className="text-xs text-muted-foreground">Accuracy</p>
                    </div>
                  </div>
                </CardContent>
              </Card>

              {/* Section breakdown */}
              <Card>
                <CardHeader><CardTitle className="text-base">Section Breakdown</CardTitle></CardHeader>
                <CardContent className="space-y-3">
                  {Object.entries(result.section_scores).map(([sec, scores]) => (
                    <div key={sec}>
                      <div className="flex justify-between text-sm mb-1">
                        <span className="font-medium">{SECTION_LABELS[sec] ?? sec}</span>
                        <span className="text-muted-foreground">{scores.correct}/{scores.total}</span>
                      </div>
                      <Progress value={(scores.correct / scores.total) * 100} className="h-2" />
                    </div>
                  ))}
                </CardContent>
              </Card>

              {/* Skill breakdown */}
              {Object.keys(result.skill_breakdown).length > 0 && (
                <Card>
                  <CardHeader><CardTitle className="text-base">Skills to Review</CardTitle></CardHeader>
                  <CardContent>
                    <div className="space-y-2">
                      {Object.entries(result.skill_breakdown)
                        .sort((a, b) => (a[1].correct / a[1].total) - (b[1].correct / b[1].total))
                        .map(([skill, scores]) => {
                          const pct = Math.round((scores.correct / scores.total) * 100);
                          return (
                            <div key={skill} className="flex items-center gap-3">
                              <div className="flex-1">
                                <div className="flex justify-between text-xs mb-1">
                                  <span className="capitalize">{skill.replace(/_/g, " ")}</span>
                                  <span className={pct >= 70 ? "text-emerald-600" : "text-red-500"}>{pct}%</span>
                                </div>
                                <Progress value={pct} className="h-1.5" />
                              </div>
                            </div>
                          );
                        })}
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Review questions */}
              <Card>
                <CardHeader><CardTitle className="text-base">Question Review</CardTitle></CardHeader>
                <CardContent className="space-y-4">
                  {result.questions_with_answers.map((q, i) => (
                    <div key={q.id} className={`p-4 rounded-lg border ${q.correct ? "border-emerald-200 bg-emerald-50" : "border-red-200 bg-red-50"}`}>
                      <div className="flex items-start gap-2">
                        {q.correct
                          ? <CheckCircle2 className="h-4 w-4 text-emerald-600 shrink-0 mt-0.5" />
                          : <XCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />}
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-medium">Q{i + 1}: {q.question_text.split('\n')[0].slice(0, 80)}...</p>
                          <div className="flex gap-4 mt-1 text-xs text-muted-foreground">
                            <span>Your answer: <strong>{q.user_answer ?? "Not answered"}</strong></span>
                            <span>Correct: <strong className="text-emerald-700">{q.correct_answer}</strong></span>
                          </div>
                          {!q.correct && (
                            <p className="text-xs mt-2 text-gray-700 leading-relaxed">{q.explanation.slice(0, 150)}...</p>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </CardContent>
              </Card>

              <Button
                onClick={() => setActiveTab("start")}
                className="w-full bg-emerald-600 hover:bg-emerald-700"
              >
                <RotateCcw className="h-4 w-4 mr-2" /> Take Another Practice Test
              </Button>
            </div>
          )}
        </TabsContent>

        {/* ── HISTORY TAB ── */}
        <TabsContent value="history" className="mt-6">
          {pastAttempts.length === 0 ? (
            <Card>
              <CardContent className="p-8 text-center text-muted-foreground">
                <BarChart3 className="h-10 w-10 mx-auto mb-3 opacity-30" />
                <p>No practice tests completed yet.</p>
                <p className="text-sm mt-1">Complete your first test to see your history here.</p>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {pastAttempts.map(attempt => (
                <Card key={attempt.id}>
                  <CardContent className="p-4 flex items-center justify-between">
                    <div>
                      <div className="flex items-center gap-2">
                        <Badge variant="outline">{attempt.test_type}</Badge>
                        {attempt.section && (
                          <Badge variant="outline" className="text-xs">
                            {SECTION_LABELS[attempt.section] ?? attempt.section}
                          </Badge>
                        )}
                      </div>
                      <p className="text-xs text-muted-foreground mt-1">
                        {new Date(attempt.completed_at).toLocaleDateString("en-US", {
                          month: "short", day: "numeric", year: "numeric",
                          hour: "2-digit", minute: "2-digit"
                        })}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-2xl font-bold text-emerald-700">{attempt.score_scaled}</p>
                      <p className="text-xs text-muted-foreground">
                        {attempt.score_raw}/{attempt.total_questions} correct
                      </p>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
